//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace AdminUI
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MenuDirectEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MenuDirectEntities object using the connection string found in the 'MenuDirectEntities' section of the application configuration file.
        /// </summary>
        public MenuDirectEntities() : base("name=MenuDirectEntities", "MenuDirectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MenuDirectEntities object.
        /// </summary>
        public MenuDirectEntities(string connectionString) : base(connectionString, "MenuDirectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MenuDirectEntities object.
        /// </summary>
        public MenuDirectEntities(EntityConnection connection) : base(connection, "MenuDirectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<order> orders
        {
            get
            {
                if ((_orders == null))
                {
                    _orders = base.CreateObjectSet<order>("orders");
                }
                return _orders;
            }
        }
        private ObjectSet<order> _orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<orderList> orderLists
        {
            get
            {
                if ((_orderLists == null))
                {
                    _orderLists = base.CreateObjectSet<orderList>("orderLists");
                }
                return _orderLists;
            }
        }
        private ObjectSet<orderList> _orderLists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<product> products
        {
            get
            {
                if ((_products == null))
                {
                    _products = base.CreateObjectSet<product>("products");
                }
                return _products;
            }
        }
        private ObjectSet<product> _products;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorders(order order)
        {
            base.AddObject("orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the orderLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorderLists(orderList orderList)
        {
            base.AddObject("orderLists", orderList);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproducts(product product)
        {
            base.AddObject("products", product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MenuDirectModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryName">Initial value of the categoryName property.</param>
        /// <param name="categoryID">Initial value of the categoryID property.</param>
        public static Category CreateCategory(global::System.String categoryName, global::System.Int32 categoryID)
        {
            Category category = new Category();
            category.categoryName = categoryName;
            category.categoryID = categoryID;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoryName
        {
            get
            {
                return _categoryName;
            }
            set
            {
                OncategoryNameChanging(value);
                ReportPropertyChanging("categoryName");
                _categoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("categoryName");
                OncategoryNameChanged();
            }
        }
        private global::System.String _categoryName;
        partial void OncategoryNameChanging(global::System.String value);
        partial void OncategoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 categoryID
        {
            get
            {
                return _categoryID;
            }
            set
            {
                if (_categoryID != value)
                {
                    OncategoryIDChanging(value);
                    ReportPropertyChanging("categoryID");
                    _categoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("categoryID");
                    OncategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _categoryID;
        partial void OncategoryIDChanging(global::System.Int32 value);
        partial void OncategoryIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MenuDirectModel", Name="order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new order object.
        /// </summary>
        /// <param name="orderDelivered">Initial value of the orderDelivered property.</param>
        /// <param name="cookingCompleted">Initial value of the cookingCompleted property.</param>
        /// <param name="orderNumber">Initial value of the orderNumber property.</param>
        public static order Createorder(global::System.Boolean orderDelivered, global::System.Boolean cookingCompleted, global::System.Int32 orderNumber)
        {
            order order = new order();
            order.orderDelivered = orderDelivered;
            order.cookingCompleted = cookingCompleted;
            order.orderNumber = orderNumber;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderDelivered
        {
            get
            {
                return _orderDelivered;
            }
            set
            {
                OnorderDeliveredChanging(value);
                ReportPropertyChanging("orderDelivered");
                _orderDelivered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDelivered");
                OnorderDeliveredChanged();
            }
        }
        private global::System.Boolean _orderDelivered;
        partial void OnorderDeliveredChanging(global::System.Boolean value);
        partial void OnorderDeliveredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean cookingCompleted
        {
            get
            {
                return _cookingCompleted;
            }
            set
            {
                OncookingCompletedChanging(value);
                ReportPropertyChanging("cookingCompleted");
                _cookingCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cookingCompleted");
                OncookingCompletedChanged();
            }
        }
        private global::System.Boolean _cookingCompleted;
        partial void OncookingCompletedChanging(global::System.Boolean value);
        partial void OncookingCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderNumber
        {
            get
            {
                return _orderNumber;
            }
            set
            {
                if (_orderNumber != value)
                {
                    OnorderNumberChanging(value);
                    ReportPropertyChanging("orderNumber");
                    _orderNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("orderNumber");
                    OnorderNumberChanged();
                }
            }
        }
        private global::System.Int32 _orderNumber;
        partial void OnorderNumberChanging(global::System.Int32 value);
        partial void OnorderNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> chefID
        {
            get
            {
                return _chefID;
            }
            set
            {
                OnchefIDChanging(value);
                ReportPropertyChanging("chefID");
                _chefID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("chefID");
                OnchefIDChanged();
            }
        }
        private Nullable<global::System.Int32> _chefID;
        partial void OnchefIDChanging(Nullable<global::System.Int32> value);
        partial void OnchefIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MenuDirectModel", Name="orderList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class orderList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new orderList object.
        /// </summary>
        /// <param name="orderLIstID">Initial value of the orderLIstID property.</param>
        /// <param name="prodID">Initial value of the prodID property.</param>
        /// <param name="orderNumber">Initial value of the orderNumber property.</param>
        public static orderList CreateorderList(global::System.Int32 orderLIstID, global::System.Int32 prodID, global::System.Int32 orderNumber)
        {
            orderList orderList = new orderList();
            orderList.orderLIstID = orderLIstID;
            orderList.prodID = prodID;
            orderList.orderNumber = orderNumber;
            return orderList;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderLIstID
        {
            get
            {
                return _orderLIstID;
            }
            set
            {
                if (_orderLIstID != value)
                {
                    OnorderLIstIDChanging(value);
                    ReportPropertyChanging("orderLIstID");
                    _orderLIstID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("orderLIstID");
                    OnorderLIstIDChanged();
                }
            }
        }
        private global::System.Int32 _orderLIstID;
        partial void OnorderLIstIDChanging(global::System.Int32 value);
        partial void OnorderLIstIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 prodID
        {
            get
            {
                return _prodID;
            }
            set
            {
                OnprodIDChanging(value);
                ReportPropertyChanging("prodID");
                _prodID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prodID");
                OnprodIDChanged();
            }
        }
        private global::System.Int32 _prodID;
        partial void OnprodIDChanging(global::System.Int32 value);
        partial void OnprodIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderNumber
        {
            get
            {
                return _orderNumber;
            }
            set
            {
                OnorderNumberChanging(value);
                ReportPropertyChanging("orderNumber");
                _orderNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderNumber");
                OnorderNumberChanged();
            }
        }
        private global::System.Int32 _orderNumber;
        partial void OnorderNumberChanging(global::System.Int32 value);
        partial void OnorderNumberChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MenuDirectModel", Name="product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new product object.
        /// </summary>
        /// <param name="prodID">Initial value of the prodID property.</param>
        /// <param name="prodName">Initial value of the prodName property.</param>
        /// <param name="prodPrice">Initial value of the prodPrice property.</param>
        /// <param name="prodCategoryName">Initial value of the prodCategoryName property.</param>
        public static product Createproduct(global::System.Int32 prodID, global::System.String prodName, global::System.Decimal prodPrice, global::System.String prodCategoryName)
        {
            product product = new product();
            product.prodID = prodID;
            product.prodName = prodName;
            product.prodPrice = prodPrice;
            product.prodCategoryName = prodCategoryName;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 prodID
        {
            get
            {
                return _prodID;
            }
            set
            {
                if (_prodID != value)
                {
                    OnprodIDChanging(value);
                    ReportPropertyChanging("prodID");
                    _prodID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("prodID");
                    OnprodIDChanged();
                }
            }
        }
        private global::System.Int32 _prodID;
        partial void OnprodIDChanging(global::System.Int32 value);
        partial void OnprodIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prodName
        {
            get
            {
                return _prodName;
            }
            set
            {
                OnprodNameChanging(value);
                ReportPropertyChanging("prodName");
                _prodName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prodName");
                OnprodNameChanged();
            }
        }
        private global::System.String _prodName;
        partial void OnprodNameChanging(global::System.String value);
        partial void OnprodNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal prodPrice
        {
            get
            {
                return _prodPrice;
            }
            set
            {
                OnprodPriceChanging(value);
                ReportPropertyChanging("prodPrice");
                _prodPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prodPrice");
                OnprodPriceChanged();
            }
        }
        private global::System.Decimal _prodPrice;
        partial void OnprodPriceChanging(global::System.Decimal value);
        partial void OnprodPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prodCategoryName
        {
            get
            {
                return _prodCategoryName;
            }
            set
            {
                OnprodCategoryNameChanging(value);
                ReportPropertyChanging("prodCategoryName");
                _prodCategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prodCategoryName");
                OnprodCategoryNameChanged();
            }
        }
        private global::System.String _prodCategoryName;
        partial void OnprodCategoryNameChanging(global::System.String value);
        partial void OnprodCategoryNameChanged();

        #endregion
    
    }

    #endregion
    
}
