//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public bool orderDelivered { get; set; }
        public bool cookingCompleted { get; set; }
        public int orderNumber { get; set; }
        public Nullable<int> chefID { get; set; }
    }
}
