//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuDirectTestSpike
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MenuDirect : DbContext
    {
        public MenuDirect()
            : base("name=MenuDirect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<order> orders { get; set; }
        public DbSet<orderList> orderLists { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<Category> Categories { get; set; }
    }
}
