//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuDirectTestSpike
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderList
    {
        public int orderLIstID { get; set; }
        public int prodID { get; set; }
        public int orderNumber { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
