//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuDirectTestSpike
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderLists = new HashSet<orderList>();
        }
    
        public int orderNumber { get; set; }
        public Nullable<bool> orderDelivered { get; set; }
        public Nullable<bool> cookingCompleted { get; set; }
    
        public virtual ICollection<orderList> orderLists { get; set; }
    }
}
