//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuDirectTestSpike
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.orderLists = new HashSet<orderList>();
        }
    
        public int prodID { get; set; }
        public string prodName { get; set; }
        public decimal prodPrice { get; set; }
        public string prodCategoryName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<orderList> orderLists { get; set; }
    }
}
